### ISSUE TITLE
Consistency

### ISSUE THREAD

**Issue by lmagoncalo** [kcochibili/TinyDB--Android-Shared-Preferences-Turbo#50]
Why some function receive as parameter a default value, for example, _getLong_ and _getDouble_ , but other functions like _getFloat_ and _getInt_ does not? It wouldn't be easier if all function received a default parameter that is return in case of error?

**Comment by AbdulelahAGR** [comment]
Yes, that is a problem with consistency. the getIn method for example, has a hardcoded default value:
`public int getInt(String key) {
        return preferences.getInt(key, 0);
    }`

You can easily clone it and modify them so that they look like:
`public int getInt(String key, int defValue) {
        return preferences.getInt(key, defValue);
    }`

Doing so for all of them which have no default value should fix the problem. I do not think this repo is still active for improvements, so it is better just to do it yourself.

**Comment by kcochibili** [comment]
Thank you for catching that error. the presence of a default value parameter in those methods is actually a mistake by me. 
for simplicity of usage, TinyDB uses a default value of 0 by default for all getNumber functions. I have now updated those methods to not include a default value parameter. Thanks again for pointing this out.

**Comment by lmagoncalo** [comment]
Understandable, but it might be necessary to change the comments to remove the default parameter.
